#!/usr/bin/env bash
# bash script to install nginx script
# index configuration + listen on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
