#!/usr/bin/env bash
# conf nginx web server redirection

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "401 $string" /etc/nginx/sites-available/default
sudo service nginx restart
