#!/usr/bin/env bash
# conf nginx web server redirection

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /usr/share/nignx/html/page_404.html
string="\\\terror_page 404 /page_404.html;\n\tlocation = /page_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "41i $string" /etc/nginx/sites-available/default

sudo service nginx restart
