#!/usr/bin/env bash
# configures a new Ubuntu machine nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.htmil
# Add redirect page
if ! grep -q "rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4" /etc/nginx/sites-available/default; then
    string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
    sudo sed -i "40i $string" /etc/nginx/sites-available/default
fi

# Add error page
if ! grep -q "error_page 404 /page_404.html;" /etc/nginx/sites-available/default; then
    echo "Ceci n'est pas une page" | sudo tee /usr/share/nignx/html/page_404.html
    string="\\\terror_page 404 /page_404.html;\n\tlocation = /page_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
    sudo sed -i "41i $string" /etc/nginx/sites-available/default
fi

# Add X-Served-By header
if ! grep -q "add_header X-Served-By" /etc/nginx/sites-available/default; then
sed -i "/server_name _;/ a\\\tadd_header X-Served-By '$HOSTNAME' always;\n" /etc/nginx/sites-available/default
sudo service nginx restart
fi
