#!/usr/bin/env bash
#configures a new Ubuntu machine nginx

sudo apt-get update
sudo apt-get install haproxy
echo "frontend web-front
	bind *:80
	default_backend web-backend
      backend web-backend
	balance roundrobin
	server 310769-web-01 54.87.216.178:80 check
	server 310769-web-02 34.207.190.13:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
