#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

x=1

while [ $x -lt 11 ]
do
	if [ $((x%4)) -ne 0 ]; then 
		echo "Best School"
	elif [ $x -eq 8 ]; then
		echo "good luck"
	else 
		echo "bad luck"
	fi
	((x+=1))
done
