#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

x=1

while [ $x -lt 21 ]
do
	echo "$x"
	case $x in
		4) echo "bad luck for China"
			;;
		8) echo "bad luck for Japan"
			;;
		17) echo "bad luck for Italy" ;;
	esac
	x=$((x+=1))
done
