#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/temp
sed -i s/127.0.0.1/127.0.0.2/ ~/temp
echo "8.8.8.8 facebook.com" >> ~/temp
cp -f ~/temp /etc/hosts
